In [ ]:
from notebook_utils import cd2parent
cd2parent()

In [7]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem

from src.descriptors import strain_energy
from src.dataloader import special_cores, Dataloader

In [8]:
dataloader = Dataloader()
dataloader.load_cores()
dataloader.load_descriptions()
dataloader.load_dft_mols()

In [9]:
mols = dataloader.dft_mols.copy()
mols.index = dataloader.smiles

In [10]:
descriptions = dataloader.descriptions.set_index('smiles')
descriptions

,QeD,logP,TPSA,SMR_VSA3,SlogP_VSA3,MR,NumNatoms,NumOatoms,dipole,3Dscore,...,PMI2,PMI3,NPR1,NPR2,RadiusOfGyration,InertialShapeFactor,Eccentricity,Asphericity,SpherocityIndex,PBF
smiles,,,,,,,,,,,,,,,,,,,,,
C1NCC12CNO2,0.403605,-1.1368,33.29,10.782935,4.837589,24.6884,2,1,3.87714,1.321493,...,248.386224,249.438373,0.325711,0.995782,1.700543,0.012257,0.945469,0.335358,0.507082,0.718026
C1NCC12CNC2,0.413406,-0.8208,24.06,10.619627,0.000000,28.1724,2,0,1.99457,1.330566,...,251.380272,253.225122,0.337851,0.992715,1.733908,0.011604,0.941199,0.319372,0.661015,0.766013
C1NCC12COC2,0.446167,-0.3938,21.26,5.309813,4.736863,26.1217,1,1,2.52334,1.321108,...,255.643938,256.254574,0.323491,0.997617,1.732046,0.012035,0.946231,0.338602,0.737560,0.798354
C1CC2(CNC2)N1,0.419327,-0.6783,24.06,10.619627,0.000000,28.2204,2,0,2.26480,1.338306,...,245.727260,247.974699,0.347370,0.990937,1.718686,0.011504,0.937728,0.307329,0.539355,0.699706
C1CNC2(C1)CNC2,0.449822,-0.2882,24.06,10.619627,0.000000,32.8374,2,0,1.15946,1.304794,...,313.077066,332.667135,0.363682,0.941112,1.848656,0.007779,0.931523,0.279286,0.605799,0.834604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C1NCC12CN2,0.366447,-1.0684,33.97,10.619627,0.000000,23.6034,2,0,2.80086,1.240647,...,166.522721,185.717503,0.344002,0.896645,1.572691,0.014035,0.938969,0.297353,0.448359,0.647464
C1CC12CNC2,0.445886,0.3698,12.03,5.309813,0.000000,24.5367,1,0,1.48063,1.260854,...,169.878248,187.622474,0.355428,0.905426,1.597255,0.013577,0.934704,0.284426,0.529917,0.712683
C1CC2(C1)CO2,0.397789,0.9393,12.53,0.000000,4.736863,22.5340,0,1,2.19762,1.249874,...,165.949763,185.283819,0.354223,0.895652,1.574122,0.013647,0.935161,0.284896,0.426321,0.593223
C1CC2(C1)CN2,0.423400,0.5123,21.94,5.309813,0.000000,24.5847,1,0,1.89748,1.248537,...,168.121599,188.474651,0.356525,0.892012,1.596512,0.013275,0.934286,0.281835,0.454073,0.661922
C1CC2(C1)CC2,0.418713,1.9505,0.00,0.000000,0.000000,25.5180,0,0,0.17218,1.279225,...,170.555901,188.314148,0.373526,0.905699,1.616318,0.012876,0.927620,0.263556,0.554481,0.762455

In [ ]:
descriptions['strain'] = dataloader.smiles.apply(strain_energy, dft_dir = 'data/cores/DFT').values
descriptions['volume'] = mols.apply(AllChem.ComputeMolVolume)
descriptions

,QeD,logP,TPSA,SMR_VSA3,SlogP_VSA3,MR,NumNatoms,NumOatoms,dipole,3Dscore,...,NPR1,NPR2,RadiusOfGyration,InertialShapeFactor,Eccentricity,Asphericity,SpherocityIndex,PBF,strain,volume
smiles,,,,,,,,,,,,,,,,,,,,,
C1NCC12CNO2,0.403605,-1.1368,33.29,10.782935,4.837589,24.6884,2,1,3.87714,1.321493,...,0.325711,0.995782,1.700543,0.012257,0.945469,0.335358,0.507082,0.718026,35.041984,95.736
C1NCC12CNC2,0.413406,-0.8208,24.06,10.619627,0.000000,28.1724,2,0,1.99457,1.330566,...,0.337851,0.992715,1.733908,0.011604,0.941199,0.319372,0.661015,0.766013,33.100433,102.824
C1NCC12COC2,0.446167,-0.3938,21.26,5.309813,4.736863,26.1217,1,1,2.52334,1.321108,...,0.323491,0.997617,1.732046,0.012035,0.946231,0.338602,0.737560,0.798354,33.741709,99.464
C1CC2(CNC2)N1,0.419327,-0.6783,24.06,10.619627,0.000000,28.2204,2,0,2.26480,1.338306,...,0.347370,0.990937,1.718686,0.011504,0.937728,0.307329,0.539355,0.699706,33.149933,102.800
C1CNC2(C1)CNC2,0.449822,-0.2882,24.06,10.619627,0.000000,32.8374,2,0,1.15946,1.304794,...,0.363682,0.941112,1.848656,0.007779,0.931523,0.279286,0.605799,0.834604,22.096024,118.344
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C1NCC12CN2,0.366447,-1.0684,33.97,10.619627,0.000000,23.6034,2,0,2.80086,1.240647,...,0.344002,0.896645,1.572691,0.014035,0.938969,0.297353,0.448359,0.647464,43.555465,87.480
C1CC12CNC2,0.445886,0.3698,12.03,5.309813,0.000000,24.5367,1,0,1.48063,1.260854,...,0.355428,0.905426,1.597255,0.013577,0.934704,0.284426,0.529917,0.712683,37.496546,91.496
C1CC2(C1)CO2,0.397789,0.9393,12.53,0.000000,4.736863,22.5340,0,1,2.19762,1.249874,...,0.354223,0.895652,1.574122,0.013647,0.935161,0.284896,0.426321,0.593223,45.027165,88.072
C1CC2(C1)CN2,0.423400,0.5123,21.94,5.309813,0.000000,24.5847,1,0,1.89748,1.248537,...,0.356525,0.892012,1.596512,0.013275,0.934286,0.281835,0.454073,0.661922,40.318028,91.680
C1CC2(C1)CC2,0.418713,1.9505,0.00,0.000000,0.000000,25.5180,0,0,0.17218,1.279225,...,0.373526,0.905699,1.616318,0.012876,0.927620,0.263556,0.554481,0.762455,34.600636,95.648

In [12]:
ref_smiles = special_cores[0]
tgt_smiles = special_cores[1:]

In [13]:
delta_perc_df = pd.DataFrame()
delta_perc_df['smiles'] = tgt_smiles
for descriptor in ['PBF','volume','dipole','strain']:
	delta_perc_df[descriptor] = delta_perc_df.smiles.apply(
		lambda x: (descriptions.loc[x,descriptor] - descriptions.loc[ref_smiles,descriptor]) * 100 / descriptions.loc[ref_smiles,descriptor]
	)

In [14]:
delta_perc_df

         smiles        PBF    volume     dipole         strain
0    C1CC12COC2  25.286099 -9.034602  62.980121  181208.914685
1  C1CC2(C1)CC2  31.039815 -1.263523 -87.237796  162827.419490
2    C1CC12CNC2  22.485641 -5.549591   9.746209  176463.674482

In [15]:
delta_df = pd.DataFrame()
delta_df['smiles'] = tgt_smiles
for descriptor in ['PBF','volume','dipole','strain']:
	delta_df[descriptor] = delta_df.smiles.apply(
		lambda x: descriptions.loc[x,descriptor] - descriptions.loc[ref_smiles,descriptor]
	)

In [16]:
delta_df

         smiles       PBF  volume   dipole     strain
0    C1CC12COC2  0.147127  -8.752  0.84969  38.483048
1  C1CC2(C1)CC2  0.180605  -1.224 -1.17696  34.579399
2    C1CC12CNC2  0.130833  -5.376  0.13149  37.475309

# 3D mol images

In [17]:
import copy
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG=True  # Use higher quality images for molecules

import py3Dmol
from src.utils import drawMol

In [18]:
current_mol = copy.copy(mols[special_cores[0]])
mol_noH = Chem.RemoveHs(current_mol)

view = py3Dmol.view()
view.addModel(Chem.MolToMolBlock(mol_noH), 'mol')
view.setStyle({'stick': {}})

view.zoomTo()
view.show()